version: "3.7"

services:
  item-app:
    image: ghcr.io/jolebo/item-app:v1 #pull image dari github packages
    ports:
      - 80:8080 # expose port ke 80
    depends_on: # dijalankan setelah item-db
      - item-db 
    restart: always # restart policy
  item-db:
    image: mongo:3 #pull image dari docker hub
    volumes:
      - app-db:/data/db #bin /data/db ke volume app-db
    restart: always # restart policy
volumes: #membuat volume
  app-db: