version: "3.7"

services:
  item-app:
    image: ghcr.io/jolebo/item-app:v1
    ports:
      - 80:8080
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    depends_on:
      - item-db
    restart: always
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always
volumes:
  app-db: